"""文件功能：集中导入算子完整性测试需要的公共对象，减少拆分后测试文件的重复样板。
作者：Egor Izmaylov
时间：2026-06-02
"""

import os

import numpy as np
import onnx
import pytest
from onnx import TensorProto, helper

import nn
from nn import Graph, Ops, Tensor, Tensor_
from nn.ONNXImport import ONNXImport
from nn.Operators import (
    CastLike,
    Clip,
    Constant,
    Concat,
    ConcatFromSequence,
    Compress,
    ConstantOfShape,
    ConvInteger,
    ConvTranspose,
    DequantizeLinear,
    Det,
    DFT,
    Dropout,
    Einsum,
    EyeLike,
    Expand,
    Flatten,
    AveragePool,
    ArgMax,
    ArgMin,
    BatchNormalization,
    BlackmanWindow,
    Cast,
    Conv,
    Gather,
    GatherElements,
    GatherND,
    GlobalAveragePool,
    GlobalLpPool,
    GlobalMaxPool,
    GridSample,
    GRU,
    HammingWindow,
    HannWindow,
    If,
    Identity,
    LSTM,
    LayerNormalization,
    LpNormalization,
    LpPool,
    LRN,
    MatMul,
    MatMulInteger,
    MelWeightMatrix,
    Max,
    MaxPool,
    MaxRoiPool,
    MaxUnpool,
    Mean,
    MeanVarianceNormalization,
    Min,
    Mod,
    Multinomial,
    NegativeLogLikelihoodLoss,
    NonMaxSuppression,
    OneHot,
    Optional,
    OptionalGetElement,
    OptionalHasElement,
    Pad,
    PRelu,
    QLinearConv,
    QLinearMatMul,
    QuantizeLinear,
    Range,
    RandomNormal,
    RandomUniform,
    RandomUniformLike,
    Bernoulli,
    Reshape,
    ReduceSum,
    Resize,
    RoiAlign,
    RNN,
    Loop,
    SequenceAt,
    SequenceConstruct,
    SequenceEmpty,
    SequenceErase,
    SequenceInsert,
    SequenceLength,
    SequenceMap,
    Shape,
    Size,
    Slice,
    Scan,
    Split,
    SplitToSequence,
    SpaceToDepth,
    Squeeze,
    SoftmaxCrossEntropyLoss,
    STFT,
    StringNormalizer,
    Sum,
    TfIdfVectorizer,
    Tile,
    TopK,
    Transpose,
    Trilu,
    NonZero,
    Unsqueeze,
    Unique,
    Where,
)
