# /**
#   ******************************************************************************
#   * @file        operator_test_context.py
#   * @author      Egor Izmaylov
#   * @brief       集中导入算子完整性测试需要的公共对象，减少拆分后测试文件的重复样板。
#   * @details     2026.06.02  V1.0.0  创建
#   ******************************************************************************
#   * @attention
#   ******************************************************************************
# */

import os

import numpy as np
import onnx
import pytest
from onnx import TensorProto, helper

import nn
from nn import Graph, Ops, Tensor, Tensor_
from nn.ONNXImport import ONNXImport
from nn.Operators import (
    ABS,
    ADD,
    AffineGrid,
    And,
    CastLike,
    BitShift,
    BitwiseNot,
    Clip,
    Constant,
    Concat,
    ConcatFromSequence,
    Compress,
    ConstantOfShape,
    ConvInteger,
    ConvTranspose,
    CumSum,
    DequantizeLinear,
    Det,
    DFT,
    Dropout,
    Einsum,
    Equal,
    EyeLike,
    Expand,
    Flatten,
    Greater,
    GreaterOrEqual,
    AveragePool,
    ArgMax,
    ArgMin,
    BatchNormalization,
    BitCast,
    BlackmanWindow,
    Cast,
    CenterCropPad,
    Col2Im,
    Conv,
    CumProd,
    Gather,
    GatherElements,
    GatherND,
    GlobalAveragePool,
    GlobalLpPool,
    GlobalMaxPool,
    GridSample,
    GRU,
    HammingWindow,
    HannWindow,
    If,
    Identity,
    Less,
    LessOrEqual,
    LSTM,
    LayerNormalization,
    LpNormalization,
    LpPool,
    LRN,
    MatMul,
    MatMulInteger,
    MelWeightMatrix,
    Max,
    MaxPool,
    MaxRoiPool,
    MaxUnpool,
    Mean,
    MeanVarianceNormalization,
    Min,
    Mod,
    Multinomial,
    NegativeLogLikelihoodLoss,
    Neg,
    NonMaxSuppression,
    Not,
    OneHot,
    Optional,
    OptionalGetElement,
    OptionalHasElement,
    Pad,
    Pow,
    PRelu,
    QLinearConv,
    QLinearMatMul,
    QuantizeLinear,
    Range,
    RandomNormal,
    RandomUniform,
    RandomUniformLike,
    Bernoulli,
    Reshape,
    ReduceSum,
    Resize,
    RoiAlign,
    RMSNormalization,
    RNN,
    Loop,
    ReduceL1,
    ReduceL2,
    ReduceLogSum,
    ReduceLogSumExp,
    ReduceMax,
    ReduceMean,
    ReduceMin,
    ReduceProd,
    ReduceSumSquare,
    SequenceAt,
    SequenceConstruct,
    SequenceEmpty,
    SequenceErase,
    SequenceInsert,
    SequenceLength,
    SequenceMap,
    Shape,
    Size,
    Slice,
    Scan,
    ScatterElements,
    ScatterND,
    TensorScatter,
    Split,
    SplitToSequence,
    SpaceToDepth,
    Squeeze,
    SoftmaxCrossEntropyLoss,
    STFT,
    SUB,
    RegexFullMatch,
    RotaryEmbedding,
    StringConcat,
    StringSplit,
    StringNormalizer,
    Sum,
    TfIdfVectorizer,
    Tile,
    TopK,
    Transpose,
    Trilu,
    MUL,
    NonZero,
    Unsqueeze,
    Unique,
    Where,
)
